### PR TITLE
Update README.md file - added teams and members

### PR DESCRIPTION
**Pull request by mafmagalhaes19**

### CODE REVIEW

**Review by filipepcampos — CHANGES_REQUESTED** [review]
Hello,
The square brackets enclosing each name are missing, so the links won't be embedded i.e John Doe (factsheets/john_doe.md) instead of [John Doe](factsheets/john_doe.md)

**Review by adr1an0s0ar3s — CHANGES_REQUESTED** [review]
Each member's name should be a link to the corresponding fact sheet (e.g. `[Adriano Soares](factsheets/adriano_soares.md) (SM)`, note the square brackets). Dispite that, all seems good! 👍

**Comment by adr1an0s0ar3s** [comment]
> Hello, The square brackets enclosing each name are missing, so the links won't be embedded i.e John Doe (factsheets/john_doe.md) instead of [John Doe](factsheets/john_doe.md)

I was in the process of writing the review when you sent yours, sorry for the duplicate request.

**Comment by mafmagalhaes19** [comment]
> Hello, The square brackets enclosing each name are missing, so the links won't be embedded i.e John Doe (factsheets/john_doe.md) instead of [John Doe](factsheets/john_doe.md)

Hi, thank you so much! My bad.. I'll change it!

**Comment by mafmagalhaes19** [comment]
> Each member's name should be a link to the corresponding fact sheet (e.g. `[Adriano Soares](factsheets/adriano_soares.md) (SM)`, note the square brackets). Dispite that, all seems good! 👍

Thank you for the example, I'll change it! 😄

**Review by filipepcampos — APPROVED** [review]
Seems good! :rocket:

**Review by adr1an0s0ar3s — APPROVED** [review]
Everything looks good! 👍

**Pull request merged**
